### ISSUE TITLE
GCP pricing missing database field information

### ISSUE THREAD

**Issue by chandlercord** [johnmuth81/cloud-compare#1]
AWS Pricing shows the following database information, GCP Pricing does not.

Total Rows: 104499 
Total Offer Code: 13 
Total Product Family: 26 
Offer type/Product Families: 50

<img width="955" alt="screen shot 2016-08-05 at 7 07 35 pm" src="https://cloud.githubusercontent.com/assets/2890337/17454102/f0c62c80-5b3f-11e6-9885-ee7a8ac0d2ad.png">
<img width="1263" alt="screen shot 2016-08-05 at 7 07 47 pm" src="https://cloud.githubusercontent.com/assets/2890337/17454103/f0c694cc-5b3f-11e6-8de3-c83133a1d13b.png">

**Comment by johnmuth81** [comment]
Fixed
